# Generated by Django 5.1.1 on 2025-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
