# Generated by Django 5.1.1 on 2025-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_image_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
