# Generated by Django 5.2 on 2025-05-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_token_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_version',
        ),
    ]
